language: python
sudo: false
dist: trusty
cache: pip
python:
  - '3.5'
  - '3.6'
install:
  - "pip install -r requirements.txt"
  - "pip install mypy"

script:
  - "python tests.py"
  - "mypy --ignore-missing-imports tunirlib/"
